# default springboot configuration file

logging:
  level:
    root: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %X{X-Request-ID:-null} %highlight(%-5level) %logger.%M - %msg%n"
  custom-header: X-Request-ID

server:
  use-forward-headers: true
