# default springboot configuration file

logging:
  level.root: info
  path: ./logs
  file: file:${logging.path}/demo.log
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %X{X-Request-ID} %highlight(%-5level) %logger.%M - %msg%n"
    file: ${logging.pattern.console}
  custom-header: X-Request-ID

server:
  use-forward-headers: true
